# Generated by Django 4.0.3 on 2022-04-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votelist',
            field=models.ManyToManyField(blank=True, related_name='voteanswerslist', to='account.profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='votelist',
            field=models.ManyToManyField(blank=True, related_name='votequestionlist', to='account.profile'),
        ),
    ]
